# Generated by Django 5.0 on 2024-01-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cantina", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="drink",
            options={"ordering": ["category__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["category__name", "name"]},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["drink", "ingredient__name"]},
        ),
        migrations.AlterUniqueTogether(
            name="purchase",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="tab",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Leave blank if customer has only one name.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, help_text="per bottle", max_digits=6
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="reorder_amount",
            field=models.IntegerField(help_text="bottles"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="reorder_point",
            field=models.IntegerField(help_text="bottles"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="stock",
            field=models.DecimalField(
                decimal_places=2, help_text="bottles", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Decimal fraction of bottle.", max_digits=4
            ),
        ),
    ]
