# Generated by Django 5.0 on 2024-01-18 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cantina", "0002_alter_customer_options_alter_drink_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IngredientCategory",
            new_name="InventoryItemCategory",
        ),
        migrations.RenameModel(
            old_name="DrinkCategory",
            new_name="MenuItemCategory",
        ),
        migrations.AlterModelOptions(
            name="menuitemcategory",
            options={"ordering": ["name"], "verbose_name_plural": "Menu categories"},
        ),
        migrations.AlterModelOptions(
            name="tab",
            options={"ordering": ["closed", "customer__last_name"]},
        ),
        migrations.RenameField(
            model_name="purchase",
            old_name="drink",
            new_name="item",
        ),
        migrations.RenameModel(
            old_name="Ingredient",
            new_name="InventoryItem",
        ),
        migrations.RenameModel(
            old_name="Drink",
            new_name="MenuItem",
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="ounces", max_digits=4
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cantina.inventoryitem",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cantina.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "ingredient__name"],
                "unique_together": {("item", "ingredient")},
            },
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
