# Generated by Django 5.0 on 2024-01-27 22:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cantina", "0004_alter_inventoryitemcategory_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("last_name", "first_name", "uba")},
        ),
    ]
