# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Cosmo's Cantina

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: github
          POSTGRES_PASSWORD: password
          POSTGRES_DB: github_testing
        ports:
          - 9311:9311
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Create config file
      run: |
        touch cosmos_cantina/config.py
        echo SECRET_KEY="\"secret_key\"" > cosmos_cantina/config.py
        echo DB_NAME="github_testing" >> cosmos_cantina/config.py
        echo DB_USER="github" >> cosmos_cantina/config.py
        echo DB_PASSWORD="password" >> cosmos_cantina/config.py
        echo DB_HOST="localhost" >> cosmos_cantina/config.py
        echo DB_PORT="9311" >> cosmos_cantina/config.py
        cat cosmos_cantina/config.py
    - name: Run migrations
      run: |
        python manage.py migrate
    - name: Test with Django
      run: |
        python manage.py test cantina
